### ISSUE TITLE
Consider supporting CentOS

### ISSUE THREAD

**Issue by johnjelinek** [mrlesmithjr/ansible-rabbitmq#1]
Maybe I can submit a PR if you don't beat me to it, but I think `RedHat` support would be great.

**Comment by mrlesmithjr** [comment]
On my to-do list already :) Getting all of my Packer templates ready for additional OS support on Ansible playbooks.

**Comment by mrlesmithjr** [comment]
@johnjelinek - All done for CentOS 7...Can spin up a 3 node cluster using Vagrant for testing if interested as well.
