### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by nlamirault** [mrlesmithjr/ansible-rabbitmq#48]
**Is your feature request related to a problem? Please describe.**
Could you please provide a  new version

**Describe the solution you'd like**
A new tag.

**Describe alternatives you've considered**

**Additional context**
We have an error to download key from Bintray
A new release with this feature could be helpful (#42)

**Comment by mrlesmithjr** [comment]
A new version has been released!

**Comment by nlamirault** [comment]
Thanks @mrlesmithjr

**Comment by nlamirault** [comment]
Thanks !
